#include "GameModuleApi.h"

#include "GrimstoneGame.h"
#include "GrimstoneRuntime.h"

#include <filesystem>

// Grimstone as a Milestone-238 runtime plugin -- the entry point a host (the
// engine's TileGridHost binary) dlopen()s via GameModuleLoader. Mirrors
// engine/games/tinytown/src/TinyTownPlugin.cpp; see GameModuleApi.h's own
// doc comment for the ABI this implements. Built against ONLY
// engine/BEditor/game-sdk/ (generated by engine/tools/update-game-sdk.sh),
// never the engine's private source directly -- see CMakeLists.txt.

namespace {

void pluginRegisterRuntime(const char* assetDir) {
    registerGrimstoneGame(std::filesystem::path(assetDir ? assetDir : "."));
}

// The project identity, same schema as project.json -- carried in the
// module so a host can set its GameProjectInfo straight from the loaded
// plugin without a separate file.
const char* const kProjectManifestJson = R"({"editorTitle": "GRIMSTONE EDITOR", "gameBinaryName": "Grimstone"})";

const BeGameModule kModule = {
    BE_GAME_MODULE_ABI_VERSION,
    kProjectManifestJson,
    pluginRegisterRuntime,
    nullptr, // registerEditor -- Grimstone has no level-generator UI to
             // register (2D plugins don't have one yet, see BEditor/CLAUDE.md)
    updateGrimstoneRuntime, // onTileGridUpdate -- Grimstone's own per-frame
                            // gameplay systems (see GrimstoneRuntime.h);
                            // more systems (combat, quests, dialogue) land
                            // there incrementally, this hookup doesn't
                            // change as they do.
};

} // namespace

extern "C" const BeGameModule* beGameModuleV1(void) { return &kModule; }
